spring.application.name=Facefixer_Backend_Project

server.port=5000

spring.security.oauth2.client.registration.google.client-id=31855937169-c4o49v3cjpcsg4ukrvln82ra445sv0ni.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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

spring.security.oauth2.client.registration.facebook.client-id=1603369500382679
spring.security.oauth2.client.registration.facebook.client-secret=2322396aa82a9fa4b833c8e91b50116d
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:5000/login/oauth2/code/google

# --- Hibernate settings ---
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# --- Supabase PostgreSQL settings ---
spring.datasource.url=jdbc:postgresql://db.ovvpkzvpsbxbxugtihqb.supabase.co:5432/postgres?user=postgres&password=Capstone@1234
spring.datasource.username=postgres
spring.datasource.password=Capstone@1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.data-source-properties.sslmode=require

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# After successful OAuth, redirect to frontend
app.oauth2.redirect-uri=http://localhost:5173/dashboard

#Sephora api
rapidapi.key=2dc199118bmsh07220e15864c16cp12658fjsn37199e082345
rapidapi.host=sephora.p.rapidapi.com

#zeel py path = C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python310\\python.exe
#aum py path = C:\\Python312\\python.exe
# --- AWS ---
aws.s3.bucket=facefixer
aws.region=us-east-2
aws.access-key=AKIA5MN3GDMMIQ3G5MPK
aws.secret-key=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
